lista=["elotes", 8, "venecia", "x"]

print("Tenemos que provocar un error asi que intentemos con el subindice 4 que no existe")

print(lista[4]) 

#Como se puede ver se logra el error ya que aunque hay 4 elementos solo llega al subindice 3, no existe un 4